version: '3'

services:
  test:
    build:
      context: .
      dockerfile: test/Dockerfile
    ports:
      - "3000:80"
    networks:
      - mynetwork

  testadmin:
    build:
      context: .
      dockerfile: testadmin/Dockerfile
    ports:
      - "3001:80"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
